// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/containers-redesign/CalmLight.tsx": () => import("../components/mockups/containers-redesign/CalmLight.tsx"),
  "./components/mockups/containers-redesign/Terminal.tsx": () => import("../components/mockups/containers-redesign/Terminal.tsx"),
  "./components/mockups/containers-redesign/WarmPro.tsx": () => import("../components/mockups/containers-redesign/WarmPro.tsx")
};
